### ISSUE TITLE
Including more GMPEs

### ISSUE THREAD

**Issue by nassermarafi** [arkottke/pygmm#3]
Is there any current effort to code up BC-Hydro and any ground-motion duration GMPEs?

**Comment by arkottke** [comment]
Nasser,

I have recently discovered that the Openquake Hazard Library (
http://docs.openquake.org/oq-hazardlib/stable/#), which might include the
BC-Hydro model. Given the number of ground motion models implemented in the
oq-hazardlib, it doesn't make sense to continue develop of this library for
the purpose of ground motion models, but rather focus on other empirical
relationships. I am in the process of adding some Vs30-kappa models. There
are no durations models currently included, but it would be a good
addition.

Albert
